# Bingo Config
grid-width: 5
season_id: 1

# Rewards based on unlock type
rewards:
  single: 100
  line: 250
  card: 5000

# Database setup
database:
  # What type of datastore to use, one of:
  # - mock: Runs an in-memory mock database, only useful for testing with no setup required
  # - primary: Uses the primary database on your Database plugin configuration
  # - secondary: Uses the primary database on your Database plugin configuration
  # Database plugin (https://github.com/OvercastCommunity/Database) is required for the later 2 options-
  type: mock
  # If using mock database, this is the configured bingo card. Ignored for primary and secondary.
  mock-data:
    - slug: 'alphabet-killer'
      name: 'Lexical Conquest'
      description: 'Strike down foes forming a linguistic chain.;It''s easy as 1 2 3;Kill them in A B C.'
      idx: 0
      hintLevel: 0
    - slug: 'anvil-killer'
      name: 'Heavy Metal'
      description: 'Crush your foe with gravity''s aid.'
      idx: 1
      hintLevel: 0

# Objective config options
big-fall:
  min-fall-height: 100
defender-kill:
  objective-max-range: 5
  objective-max-size: 40
eating:
  foods-required: 3
flower-pot:
  allow-any: false
hedgehog:
  min-arrows: 25
icarus-height:
  min-vertical-velocity: 6 # About 100 blocks in the air
  delay-ticks: 2
kill-streak:
  required-streak: 10
match-length:
  required-mins: 60
picky-voter:
  min-map-votes: 4
  max-map-votes: 4
player-craft:
  material-name: "PISTON_BASE"
player-shifting:
  radius: 4
  same-team-count: 1
  other-team-count: 2
quick-kills:
  kills-required: 3
  time-threshold-seconds: 5
water-dropper:
  min-fall-height: 100
wool-collector:
  min-wool-count: 5