# Bingo Config
enable: true
debug: false
grid-width: 5

# Rewards based on unlock type
rewards:
  single: 100
  line: 250
  card: 5000

# Objective config options
big-fall:
  min-fall-height: 100
defender-kill:
  objective-max-range: 5
  objective-max-size: 30
eating:
  foods-required: 3
hedgehog:
  min-arrows: 25
icarus-height:
  min-vertical-velocity: 6 # About 100 blocks in the air
kill-streak:
  required-streak: 10
match-length:
  required-mins: 60
picky-voter:
  min-map-votes: 4
  max-map-votes: 4
player-craft:
  material-name: "PISTON_BASE"
player-shifting:
  min-range: 8
  same-team-count: 1
  other-team-count: 2
quick-kills:
  kills-required: 3
  time-threshold-seconds: 5
water-dropper:
  min-fall-height: 100
wool-collector:
  min-wool-count: 5